version: '3'
services:
  app:
    container_name: transaction_service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "3031:3030" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped